import random
num1 = random.randint(0,9)
num2 = random.randint(0,9)
num3 = random.randint(0,9)
digit1 = random.randint(1,6)
digit2 = random.randint(1,6)
digit3 = random.randint(1,6)
digit4 = random.randint(1,6)
print(f"Three digit code (0-9): {num1} {num2} {num3}")
print(f"Four digit code (1-6): {digit1} {digit2} {digit3} {digit4}")
